export const routePaths = {
    home: '/',
    aiTutor: '/ai-tutor',
    aiTutorChat: '/ai-tutor/mentors/:mentorId/scenes/:sceneId',
    awakening: '/awakening',
    awakeningCourse: '/awakening/courses/:courseId',
    login: '/login',
    profile: '/profile',
    knowledgeGaps: '/profile/knowledge-gaps',
    notebook: '/profile/notes',
    notebookCourse: '/profile/notes/courses/:coursePackageId',
    notebookChapter: '/profile/notes/courses/:coursePackageId/chapters/:chapterId',
    learningProgress: '/profile/learning-progress',
    favorites: '/profile/favorites',
    works: '/profile/works',
    foreignLanguageGuide: '/foreign-language-guide',
    foreignLanguageCourse: '/foreign-language-guide/courses/:courseId',
    collaboration: '/collaboration',
    vipMembership: '/vip',
    leaderboard: '/leaderboard',
    prizeCenter: '/prize-center',
    promotionRevenue: '/promotion/revenue',
    branchCompany: '/branch-company',
    courseSearch: '/courses/search',
} as const
