export const routePaths = {
    home: '/',
    awakening: '/awakening',
    awakeningCourse: '/awakening/courses/:courseId',
    login: '/login',
    profile: '/profile',
    knowledgeGaps: '/profile/knowledge-gaps',
    notebook: '/profile/notes',
    notebookCourse: '/profile/notes/courses/:coursePackageId',
    notebookChapter: '/profile/notes/courses/:coursePackageId/chapters/:chapterId',
    learningProgress: '/profile/learning-progress',
    favorites: '/profile/favorites',
    works: '/profile/works',
    foreignLanguageGuide: '/foreign-language-guide',
    foreignLanguageCourse: '/foreign-language-guide/courses/:courseId',
    leaderboard: '/leaderboard',
    promotionRevenue: '/promotion/revenue',
    courseSearch: '/courses/search',
} as const
